medicines/urls.py
from django.conf.urls import url
from . import views


app_name = 'medicines'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[A-Z,a-z]+)/$', views.DetailView.as_view(), name="product_list"),
]

test_izabel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^medicines/', include('medicines.urls')),
    url(r'^', include('medicines.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicines/models.py
from django.db import models


class Products(models.Model):
    product_type = models.CharField(max_length=250, primary_key=True)
    product_logo = models.FileField()
    product_description = models.CharField(max_length=10000)


class Medicine(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    med_name = models.CharField(max_length=250, primary_key=True)
    med_description = models.CharField(max_length=10000)
    med_price = models.CharField(max_length=250)
    med_logo = models.FileField()
    manufacturer = models.CharField(max_length=250)


class Specification(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    salt = models.CharField(max_length=100)
    salt_quantity = models.CharField(max_length=10)

medicines/views.py
from .models import Products, Medicine
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'medicines/index.html'

    def get_queryset(self):
        return Products.objects.all()


class DetailView(generic.DetailView):
    model = Products
    template_name = 'medicines/product_list.html'


# Create your views here.
# def index(request):
#     products = Products.objects.all()
#     html = ''
#     for product in products:
#         url = str(product.id) + '/'
#         html += '<a href = " ' + url + '">' + product.product_type + '</a><br>'
#     return HttpResponse(html)

# def index(request):
#     products = Products.objects.all()
#     template = loader.get_template('medicines/index.html')
#     context = {
#         'all_products': products,
#     }
#     return HttpResponse(template.render(context, request))

# def index(request):
#     products = Products.objects.all()
#     context = {'all_products': products}
#     return render(request, 'medicines/index.html', context)
#
#
# def product_list(request, product_id):
#     try:
#         product = Products.objects.get(pk=product_id)
#     except Products.DoesNotExist:
#         raise Http404("The contents of this product does not exist")
#
#     return render(request, 'medicines/product_list.html', {'product': product})

medicines/templates/medicines/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>
    {% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <link href="{% static "medicines/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static "medicines/vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <!-- Plugin CSS -->
    <link href="{% static "medicines/vendor/magnific-popup/magnific-popup.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->

    <link href="{% static "medicines/css/agency.min.css" %}" rel="stylesheet">
    <link href="{% static "medicines/css/creative.min.css" %}" rel="stylesheet">
</head>
<body id="page-top">
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href={% block about %}"#about"{% endblock %}>About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href={% block services %}"#services"{% endblock %}>Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href={% block portfolio %}"#portfolio"{% endblock %}>Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href={% block contact %}"#contact"{% endblock %}>Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% endblock %}
{% block body %}
{% endblock %}
    <section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h2 class="section-heading">Let's Get In Touch!</h2>
        <hr class="my-4">
        <p class="mb-5">Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ml-auto text-center">
        <i class="fa fa-phone fa-3x mb-3 sr-contact"></i>
        <p>123-456-6789</p>
      </div>
      <div class="col-lg-4 mr-auto text-center">
        <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
        <p>
          <a href="https://www.gmail.com">feedback@startbootstrap.com</a>
        </p>
      </div>
    </div>
  </div>
</section>

 <!-- Bootstrap core JavaScript -->
    <script src="{% static "medicines/vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "medicines/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static "medicines/vendor/jquery-easing/jquery.easing.min.js" %}"></script>
    <script src="{% static "medicines/vendor/scrollreveal/scrollreveal.min.js" %}"></script>
    <script src="{% static "medicines/vendor/magnific-popup/jquery.magnific-popup.min.js" %}"></script>



    <!-- Custom scripts for this template -->
    <script src="{% static "medicines/js/creative.min.js" %}"></script>
    <script src="{% static "medicines/js/agency.min.js" %}"></script>

</body>
</html>

medicines/templates/medicines/index.html
{% extends 'medicines/base.html' %}
{% block title %}Izabel{% endblock %}
{% block body %}
{% load staticfiles %}
<header class="masthead text-center text-white d-flex">
  <div class="container my-auto">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>Your Favorite Source of Free Bootstrap Themes</strong>
        </h1>
        <hr>
      </div>
      <div class="col-lg-8 mx-auto">
        <p class="text-faded mb-5">Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!</p>
        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
      </div>
    </div>
  </div>
</header>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h2 class="section-heading text-white">We've got what you need!</h2>
        <hr class="light my-4">
        <p class="text-faded mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
        <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a>
      </div>
    </div>
  </div>
</section>

<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">At Your Service</h2>
        <hr class="my-4">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-diamond text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Sturdy Templates</h3>
          <p class="text-muted mb-0">Our templates are updated regularly so they don't break.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-paper-plane text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Ready to Ship</h3>
          <p class="text-muted mb-0">You can use this theme as is, or you can make changes!</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-newspaper-o text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Up to Date</h3>
          <p class="text-muted mb-0">We update dependencies to keep things fresh.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-heart text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Made with Love</h3>
          <p class="text-muted mb-0">You have to make your websites with love these days!</p>
        </div>
      </div>

    </div>
  </div>

</section>
<section class="p-1" >
    <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Our Products</h2>
        <hr class="my-4">
      </div>
    </div>
  </div>
</section>

<section class="p-1" id="portfolio">
  <div class="container-fluid p-0">
      <div class="row no-gutters">
        {% for product in object_list %}
        <div class="col-lg-4 col-sm-6">
        <a class="portfolio-box" href="{% url 'medicines:product_list' product.product_type %}">
          <img class="img-fluid" src="{{ product.product_logo.url }}" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                {{ product.product_type }}
              </div>
              <div class="project-name">
                {{ product.product_description }}
              </div>
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<section class="bg-dark text-white">
  <div class="container text-center">
    <h2 class="mb-4">Free Download at Start Bootstrap!</h2>
    <a class="btn btn-light btn-xl sr-button" href="http://startbootstrap.com/template-overviews/creative/">Download Now!</a>
  </div>
</section>
{% endblock %}

medicines/templates/medicines/product_list.html
{% extends 'medicines/base.html' %}
{% block navbar %}
    {% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand " href="{% url 'medicines:index' %}">Start Bootstrap</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href={% block contact %}"#contact"{% endblock %}>Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}
{% block body %}
    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Here are the medicines of the product {{ products.product_type }}</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <a class="btn btn-primary btn-xl js-scroll-trigger" href="#portfolio">Explore Medicines</a>
          </div>
        </div>
      </div>
    </header>

     <!-- Portfolio Grid -->
    <section class="bg-light" id="portfolio">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Medicines</h2>
            <h3 class="section-subheading text-muted">Made with Care</h3>
          </div>
        </div>
        <div class="row">
          {% for medicine in products.medicine_set.all %}
          <div class="col-md-4 col-sm-6 portfolio-item">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal{{ medicine.med_name }}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{ medicine.med_logo.url }}" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>{{ medicine.med_name }}</h4>
              <p class="text-muted">{{ medicine.med_description }}</p>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </section>

    {%  for medicine in products.medicine_set.all %}
    <div class="portfolio-modal modal fade" id="portfolioModal{{ medicine.med_name }}" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="close-modal" data-dismiss="modal">
            <div class="lr">
              <div class="rl"></div>
            </div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-lg-8 mx-auto">
                <div class="modal-body">
                  <!-- Project Details Go Here -->
                  <h2 class="text-uppercase">{{ medicine.med_name }}</h2>
                  <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                  <img class="img-fluid d-block mx-auto" src="{% static 'medicines/img/portfolio/medicine1.jpg' %}" alt="">
                  <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
                  <ul class="list-inline">
                    <li>Date: January 2017</li>
                    <li>Client: Threads</li>
                    <li>Category: Illustration</li>
                  </ul>
                  <button class="btn btn-primary" data-dismiss="modal" type="button">
                    <i class="fa fa-times"></i>
                    Close Project</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
{% endblock %}